### ISSUE TITLE
Number of comments not always showing

### ISSUE THREAD

**Issue by Kadoffe** [Sommerregen/grav-plugin-jscomments#17]
Hi there Benny,

in cooperation with the Grav team we are building a new theme for my site and use your plugin to display Disqus comments. 
The problem is that it's not always showing up and the can't figure out what exactly causes it.
I could send you the login informations to have a look yourself. Maybe you got a good guess how to solve it.

Greets,

Kadoffe

**Comment by Sommerregen** [comment]
Hi @Kadoffe ,

I can join in Tuesday at earliest. As a first guess, you may check whether the JavaScript is loaded or not. And whether the service is reachable. In principle I may see one issue in the code: As per [disqus.html.twig#L47](https://github.com/Sommerregen/grav-plugin-jscomments/blob/develop/templates/plugins/jscomments/disqus.html.twig#L47), both the JS for the comments and the comments counter itself are loaded asynchronously. It may happen that the comments counter loads before the actual JS for the comments and that's why it is not considered. One has to make sure that first the JS for the comments is loaded and then the code for the comments counter.

If you or the Grav Team comes up with a solution, I would be happy to merge it :-)

**Comment by Kadoffe** [comment]
Hi @Sommerregen ,
the console of the browser tools doesn't show any errors so the JS should be loaded.
But funny things like this happen: http://imgur.com/a/GPvB0

**Comment by Sommerregen** [comment]
@Kadoffe ,

mh, strange. Do you load the JS only once, or was it loaded for every card in the image? Maybe loading it multiple times interferes somehow with the presentation.

**Comment by Kadoffe** [comment]
@Sommerregen 

if I'm not mistaken it only loads once at the end:
http://imgur.com/a/qdsrQ

**Comment by Sommerregen** [comment]
@Kadoffe This screenshot indicates that you are not using my plugin or use a custom version. You may read https://help.disqus.com/customer/portal/articles/565624-adding-comment-count-links-to-your-home-page in this case, that helps you to set it up correctly.

**Comment by Kadoffe** [comment]
@Sommerregen I can't really tell because I don't have direct access to the theme files but what would be the correct way to load it with your plugin?

**Comment by Sommerregen** [comment]
@Kadoffe To be honest, the functionality in the screenshot you showed me, is not possible. My plugin is designed to provide just a comments section for every page that optionally displays the comment counts directly above the comments.

The correct way to load comments is given in the link I posted earlier. The crucial thing is to set a class `disqus-comment-count` as well as an attribute `data-disqus-identifier` or `data-disqus-url` to the HTML element.

**EDIT:** I will close this issue for now as it is not related to this plugin and your issue is more of a general question. Please feel free to open it again, when you have access to your site and your are still looking for an alternate solution.
