### ISSUE TITLE
Not Working.

### ISSUE THREAD

**Issue by oldmanumby** [Sommerregen/grav-plugin-jscomments#25]
I'm using the latest version of GRAV with the Gantry Framework. I have been unable to get JSComments to work. I'm using Disqus commenting, which is working fine. I've used the plugin successfully in the past, and everything looks normal with the plugin, just not showing on the blog pages.

Suggestions?

**Comment by Sommerregen** [comment]
Hi @sigillumrasa ,

I think this is a Gantry issue as you can [see in the diff](https://github.com/Sommerregen/grav-plugin-jscomments/compare/v2.1.4...develop), I haven't changed anything - only added stuff.

In order to debug this, can you specify which theme are you using? And double check to have something like

```twig
{% if config.plugins.jscomments.enabled %}
  {{ jscomments()|raw }}
{% endif %}
```

in your partial? The `raw` filter is important here, as Gantry escapes all output by default. Otherwise can you debug your site, i.e., with the browsers inspector, search for the output [disqus.html.twig#L18-L33](https://github.com/Sommerregen/grav-plugin-jscomments/blob/develop/templates/plugins/jscomments/disqus.html.twig#L18-L33), and show me the content?

**Comment by oldmanumby** [comment]
DOH! ... Refreshed cache, working now. THX!
